name: Build on Linux

on: [push, pull_request]

jobs:
  build:
    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure GIT
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: |
        git config --global advice.detachedHead false
        git submodule update --init --recursive

    - name: Test with echo 1
      shell: bash
      run: echo test

    - name: Test list environment variables
      shell: bash
      run: env

    - name: Test with echo 2
      shell: bash
      run: echo test WORKSPACE=${{env.GITHUB_WORKSPACE}}

    - name: Test current directory
      working-directory: ${{env.GITHUB_WORKSPACE}}/ci/github
      shell: bash
      run: |
        pwd

    - name: List environment variables
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: env

    - name: List files in directory 'github'.
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: ls

    - name: Install Google Test
      working-directory: ${{env.GITHUB_WORKSPACE}}/ci/github
      shell: bash
      run: ./install_googletest.sh

    - name: Build library
      working-directory: ${{env.GITHUB_WORKSPACE}}/ci/github
      shell: bash
      run: ./build_library.sh

    - name: Build client
      working-directory: ${{env.GITHUB_WORKSPACE}}/ci/github
      shell: bash
      run: ./build_client.sh

    - name: Run unit tests
      working-directory: ${{env.GITHUB_WORKSPACE}}/ci/github
      shell: bash
      run: ./test_script.sh

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-results
        path: build/bin/rapidassist_unittest*.xml
