name: Build on Linux

on: [push, pull_request]

env:
  # build Configuration, i.e. Debug, Release, etc.
  Configuration: Release

  # Required for Github Action. Unit test TestProcess.testKillAndTerminate fails to start /bin/nano with the following error: "Error opening terminal: unknown."
  TERM: xterm

jobs:
  build:
    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure GIT
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: |
        git config --local core.autocrlf true
        git config --local advice.detachedHead false
        git submodule update --init --recursive

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: List environment variables for debugging
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: |
        env

    - name: Configure user profile and directories
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: |
        mkdir ~/Documents   #required for TestUser.testFoldersExisting() because /home/travis/Documents does not exists!
        mkdir ~/Desktop     #required for TestUser.testFoldersExisting() because /home/travis/Desktop   does not exists!
        
    - name: Install Google Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: ./ci/github/install_googletest.sh

    - name: Build library
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: ./ci/github/build_library.sh

    - name: Build client
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: ./ci/github/build_client.sh

    - name: Run unit tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: ./ci/github/test_script.sh

    - name: Search unit test report file
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: |
        UNITTEST_REPORT_PATH=$(find . -name 'rapidassist_unittest*.xml')
        echo UNITTEST_REPORT_PATH=$UNITTEST_REPORT_PATH
        echo UNITTEST_REPORT_PATH=$UNITTEST_REPORT_PATH >> $GITHUB_ENV
      
    - name: Creating test badge
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: python ci/github/maketestbadge.py ${{env.UNITTEST_REPORT_PATH}}

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-results
        path: build/bin/rapidassist_unittest*.xml
