name: Build on Windows

on: [push, pull_request]

env:
  PlatformToolset: v140

  # build platform, i.e. x86, x64, Any CPU. This setting is optional.
  Platform: Win32

  # build Configuration, i.e. Debug, Release, etc.
  Configuration: Release

jobs:
  build:
    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure GIT
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        git config --local core.autocrlf true
        git config --local advice.detachedHead false
        git submodule update --init --recursive

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: List environment variables for debugging
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        set

    - name: Find permissions of files and directories in C:\
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        call ci\github\install_sysinternals.bat
        ci\github\bin\accesschk64.exe -d -nobanner /accepteula "%USERNAME%" c:\*.*

    - name: Install Google Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: call ci\github\install_googletest.bat

    - name: Build library
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: call ci\github\build_library.bat

    - name: Build client
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: call ci\github\build_client.bat

    - name: Run unit tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: call ci\github\test_script.bat

    - name: Search unit test report file
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        for /f "tokens=* usebackq" %%f in (`dir/b/s build\bin\${{env.configuration}}\rapidassist_unittest*.xml`) do (set UNITTEST_REPORT_PATH=%%f)
        echo UNITTEST_REPORT_PATH=%UNITTEST_REPORT_PATH%
        echo UNITTEST_REPORT_PATH=%UNITTEST_REPORT_PATH% >> $GITHUB_ENV
      
    - name: Creating test badge
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        set
        python ci\github\maketestbadge.py ${{env.UNITTEST_REPORT_PATH}}
      
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-results
        path: build\bin\${{env.Configuration}}\rapidassist_unittest*.xml
