name: Build on Linux

on: [push, pull_request]

jobs:
  build:
    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure GIT
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        git config --global advice.detachedHead false
        git submodule update --init --recursive

    - name: Install Google Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./$GITHUB_WORKSPACE/ci/github/install_googletest.sh

    - name: Build library
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./$GITHUB_WORKSPACE/ci/github/build_library.sh

    - name: Build client
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./$GITHUB_WORKSPACE/ci/github/build_client.sh

    - name: Run unit tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./$GITHUB_WORKSPACE/ci/github/test_script.sh

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-results
        path: build/bin/rapidassist_unittest*.xml
