name: Build and Test - Windows

on: [push]

env:
  PlatformToolset: v140

  # build platform, i.e. x86, x64, Any CPU. This setting is optional.
  Platform: Win32

  # build Configuration, i.e. Debug, Release, etc.
  Configuration: Release

jobs:
  build:
    # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure GIT
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        git config --global core.autocrlf true
        git config --global advice.detachedHead false
        git submodule update --init --recursive

    - name: Install Google Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: call ci\github\install_googletest.bat

    - name: Build library
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: call ci\github\build_library.bat

    - name: Build client
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: call ci\github\build_client.bat

    - name: Run unit tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: call ci\github\test_script.bat

    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: unit-test-results
        path: build\bin\${{env.Configuration}}\rapidassist_unittest*.xml
